# Automatically updated by the winget bot at 2024/Oct/19
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: Zoho.TrueSync
PackageVersion: 3.9.8
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
PackageUpdate: false
PackageUrl : https://files-accl.zohopublic.com/public/tswin/download/6e5dc09390933f54b9da77838c984d7b
