# Automatically updated by the winget bot at 2024/Nov/07
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Zoho.TrueSync
PackageVersion: 3.9.15
InstallerLocale: en-US
InstallerType: msi
ProductCode: '{CDD49994-675D-47EB-B32B-2274F0D9FED1}'
Installers:
- InstallerUrl: https://files-accl.zohopublic.com/public/tsbin/download/d501492ef336331284839784096b057b
  Architecture: x64
  InstallerSha256: 9e18c2b7e0f307355de2473dec845f174c8a20ed648796afe98f6e87cb301821
ManifestType: installer
ManifestVersion: 1.6.0
